version: '3.1'

services:
  database:
    image: postgres:14.5
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/database
volumes:
  db:


